#include "common.h"

// max length of strings
const unsigned long max_size = 2000;
// number of closest words that will be shown
const long long N = 40;
// max length of vocabulary entries
const long long max_w = 50;

// Load the binary vector file generated by word2vec project
void word2vec_model_load(word2vec_model* model, char* file_name) {
  FILE *f;
  f = fopen(file_name, "rb");
  if (f == NULL) {
    rb_raise(rb_eArgError, "file not found");
    return;
  }
  
  long long words, size;
  fscanf(f, "%lld", &words);
  fscanf(f, "%lld", &size);
  model->word_count = words;
  model->vector_dim = size;
  
  model->vocabulary = ZALLOC_N(char, (long long)words * max_w);
  model->vectors = ALLOC_N(float, model->word_count * model->vector_dim);
  if (model->vectors == NULL) {
    rb_raise(rb_eNoMemError, "Cannot allocate memory: %lld MB    %lld  %lld\n", (long long)words * size * sizeof(float) / 1048576, words, size);
    return;
  }

  for (long long b = 0; b < words; b++) {
    long long a = 0;
    while (true) {
      model->vocabulary[b * max_w + a] = fgetc(f);
      if (feof(f) || (model->vocabulary[b * max_w + a] == ' ')) break;
      if ((a < max_w) && (model->vocabulary[b * max_w + a] != '\n')) a++;
    }
    model->vocabulary[b * max_w + a] = 0;
    for (a = 0; a < size; a++) fread(&model->vectors[a + b * size], sizeof(float), 1, f);
    float len = 0;
    for (a = 0; a < size; a++) len += model->vectors[a + b * size] * model->vectors[a + b * size];
    len = sqrt(len);
    for (a = 0; a < size; a++) model->vectors[a + b * size] /= len;
  }
  fclose(f);
}